[theme]
# Primary accent color for interactive elements.
primaryColor = "#cf619f"

# Background color for the main content area.
backgroundColor = "#00172B"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#01213d"

# Color used for almost all text.
textColor = "#C0C0C0"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"